base_url = "https://pikerpapers.github.io/piker-papers"
title = "The Piker Papers"
description = "Structured, searchable files with source-backed documentation."
default_language = "en"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
  { name = "categories", paginate_by = 20, feed = true },
  { name = "severity", paginate_by = 20, feed = true },
  { name = "entry_type", paginate_by = 20, feed = true },
  { name = "tags", paginate_by = 20, feed = true }
]

[markdown]
render_emoji = false
external_links_target_blank = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
ga4_measurement_id = "G-RFR1H71T4Y"
sentry_loader_src = "https://js-de.sentry-cdn.com/8e2a70880f0e0ffc6ea774b0ab22f8d2.min.js"
sentry_dsn = "https://8e2a70880f0e0ffc6ea774b0ab22f8d2@o4511129617498112.ingest.de.sentry.io/4511129620709456"
sentry_environment = ""
sentry_traces_sample_rate = 0.0
